---
title: "Short bio"
description: |
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#### Education 

**PhD** | New York University, 2022 <br> 
**MPhil** | New York University, 2021 <br> 
**MBA** | University of Chicago, 2014  <br>
**BA, Economics** | Harvard University, 2009 <br> 

*How you can contact me*: zilinsky (at) nyu.edu

At TUM, I have been writing papers about conspiracy theories, toxic online speech, content moderation, and social status.

I did my PhD at NYU where I wrote several papers about social media and political participation. Prior to coming to NYU and worked on projects related to [discrimination](https://www.sciencedirect.com/science/article/pii/S2214658X1630006X), [inclusive capitalism](https://piie.com/publications/piie-briefings/raising-lower-level-wages-when-and-why-it-makes-economic-sense), and behavioral economics. Most of these projects were done at MIT and at the Peterson Institute for International Economics.

My goal is to improve our understanding of the connection between voting, economic outcomes, public opinion, and the media through rigorous research. 

### Teaching

At TUM, I have taught the following MA courses:

- Political Behavior, Insurgent Politics and Conspiracy Theories
- Telling Stories with R and Data Visualizations
- Campaigns, Elections, and Social Media
- Psychology of Persuasion

<br>

As a Data Fellow at NYU, I have advised undergraduate students on research design, tidying data, and interpreting empirical results. My teaching experience is in three fields:

- *Political Science* (see above).
- *Data Science*: Taught topics in machine learning including model selection, false discovery rates, classification and decision trees, the bootstrap and cross-validation. I am also interested in teaching data visualization and text-as-data. 
- *Economics*: Designed and taught a course on experimental economics. TA-ed a large Behavioral Economics course led by David Laibson and Andrei Shleifer.
  - [Course Overview](files/teaching/970-summary.pdf) | [Syllabus and readings](https://github.com/zilinskyjan/archive/blob/master/teaching/Harvard/Economics_970.pdf).


---