---
title: "Jan Zilinsky"
description: |
  Post-doctoral research fellow
site: distill::distill_website
twitter:
  site: '@janzilinsky'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Can add to _site.yml:
# cookie_consent:
#   style: simple
#   type: express
#   palette: light
#   lang: en
#   cookies_policy: url

# https://rstudio.github.io/distill/publish_website.html#github-pages

# Lecturer at the Chair of Digital Governance, TUM School of Social Sciences and Technology.
# My academic work evaluates the narratives surrounding the 2016 U.S. presidential election, and the relationship between economic sentiment and objective economic outcomes.
# I study the impact of social media on American politics. 
# In ongoing work at the [Center for Social Media and Politics](https://csmapnyu.org), my co-authors and I investigate how media consumption and exposure to misinformation influences voters' beliefs and decisions.
```

**Core research interests:** Public Opinion, Technology & Politics, Political Methodology. ([Google Scholar](https://scholar.google.com/citations?user=bHW37e4AAAAJ&hl=en&oi=ao))

I study how citizens digest political information, economic news, and controversial content -- toxic speech, conspiracy rhetoric, disinformation -- from online platforms, state actors, and political entrepreneurs. 

# Latest

* The code and some materials for my Data Visualization class are now [publicly available](http://zilinskyjan.github.io/DataViz/).
- Presented new work on citizens' skepticism of technology (AI, social media, modern medicine) at the APSA [Political Communication pre-conference](https://cpg.comm.ucla.edu/preconf2023/) on Aug. 30 at UCLA.
* July 2023: I was a lecturer at the the Summer Institute in Computational Social Science: Lecture 1 ([html](https://rawcdn.githack.com/zilinskyjan/lectures/b3d8aecd8a13677015ee7bdee12d24fe0e3ef98d/SICSS/SICSS_01_digital_trace_data.html); [pdf](https://zilinskyjan.github.io/slides/SICSS_Digital_trace_data)), [Lecture 2](https://rawcdn.githack.com/zilinskyjan/lectures/b3d8aecd8a13677015ee7bdee12d24fe0e3ef98d/SICSS/SICSS_02_screenscraping.html#/title-slide), [Lecture 3](https://rawcdn.githack.com/zilinskyjan/lectures/b3d8aecd8a13677015ee7bdee12d24fe0e3ef98d/SICSS/SICSS_03_applications.html#/title-slide).


## Publications

- Exposure to the Russian Internet Research Agency foreign influence campaign on Twitter in the 2016 US election and its relationship to attitudes and voting behavior. 2023. With Gregory Eady, Tom Paskhalis, Richard Bonneau, Jonathan Nagler and Joshua A. Tucker. **Nature Communications**. [Published paper (open-access)](https://www.nature.com/articles/s41467-022-35576-9). [Short summary](https://csmapnyu.org/news-views/news/exposure-to-russian-twitter-campaigns-in-2016-presidential-race-highly-concentrated-largely-limited-to-strongly-partisan-republicans). Coverage: [Washington Post](https://www.washingtonpost.com/politics/2023/01/09/russian-trolls-twitter-had-little-influence-2016-voters/), [Nieman Journalism Lab](https://www.niemanlab.org/2023/01/good-news-misinformation-isnt-as-powerful-as-feared-bad-news-neither-is-information/), [The Hill TV](https://www.youtube.com/watch?v=baFTYloKpCI), [Wall Street Journal](https://www.wsj.com/articles/does-twitter-disinformation-even-work-russian-trolls-2016-election-nature-communications-study-elon-musk-donald-trump-vladimir-putin-11673375453), [The Intercept](https://theintercept.com/2023/01/10/russia-twitter-bots-trump-election/), [Tech Policy Press podcast](https://techpolicy.press/examining-the-impact-of-internet-research-agency-tweets-in-the-2016-u-s-election/), [Columbia Journalism Review](https://www.cjr.org/the_media_today/nature_study_trump_bots_twitter.php), [Other](https://nature.altmetric.com/details/140986471/news)

- Division Does Not Imply Predictability: Demographics Continue to Reveal Little About Voting and Partisanship. 2022. **Political Behavior**. With [Seo-young Silvia Kim](https://sysilviakim.com). <br>
[Published paper (open-access)](https://link.springer.com/article/10.1007/s11109-022-09816-z) | [Pre-print](https://preprints.apsanet.org/engage/apsa/article-details/607dd8cb331f302dc365f87e) | [Code on Github](https://github.com/sysilviakim/surveyML) | [MPSA Slides](https://zilinskyjan.github.io/slides/surveyML_MPSA.pdf) | [Podcast](https://www.niskanencenter.org/is-demographic-and-geographic-polarization-overstated/)

- Geographic Boundaries and Local Economic Conditions Matter for Views of the Economy. 2022. **Political Analysis**. With [James Bisbee](https://www.jamesbisbee.com). <br>
[Paper](https://www.cambridge.org/core/journals/political-analysis/article/abs/geographic-boundaries-and-local-economic-conditions-matter-for-views-of-the-economy/32C8C058B8E16CAD48374F95B2B1B3EF) | [Code and data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/C1XZKK)

- Don’t Republicans Tweet Too? Using Twitter to Assess the Consequences of Political Endorsements by Celebrities. **Perspectives on Politics**, 2020. With Vaccari, C., Nagler, J. & Tucker, J. A.
[PDF](https://www.cambridge.org/core/journals/perspectives-on-politics/article/abs/dont-republicans-tweet-too-using-twitter-to-assess-the-consequences-of-political-endorsements-by-celebrities/B2915BB8FBD93D0555D8C3D77CB00E65) | [Monkey Cage summary](https://www.washingtonpost.com/politics/2019/10/28/think-celebrities-get-punished-being-political-fact-they-get-retweeted/)

- Democratic deconsolidation revisited: Young Europeans are not dissatisfied with democracy.
**Research & Politics**, 2019. [PDF (open-access)](https://journals.sagepub.com/doi/10.1177/2053168018814332)

- How Many People Live in Political Bubbles on Social Media? Evidence from Linked Survey and Twitter Data. **Sage Open**, 2019. With Gregory Eady, Jonathan Nagler, Andrew Guess, and Joshua Tucker.
[PDF (open-access)](https://journals.sagepub.com/doi/full/10.1177/2158244019832705) | Summaries: [Pacific Standard](https://psmag.com/news/ideological-bubbles-turns-out-liberals-and-conservatives-mainly-follow-the-same-news-sources), [Main chart](https://twitter.com/andyguess/status/1102962970227810304) 

- The Happiness Gap in Eastern Europe. **Journal of Comparative Economics**, 2016. With Simeon Djankov and Elena Nikolova.
[PDF](http://www.sciencedirect.com/science/article/pii/S0147596715000888) | Summary: [Financial Times blog](https://www.ft.com/content/abae03a5-6b58-3f05-ac84-d298b0e47ab5) | Ungated [SSRN](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2658136) & [OSF](https://osf.io/preprints/socarxiv/et7vz/) pre-prints

## Preprints and ongoing work

- Donate To Help Us Fight Back: Mobilization Rhetoric in Political Fundraising. With Seo-young Silvia Kim and Brian Brew. <br> 
[APSA Preprint](https://preprints.apsanet.org/engage/apsa/article-details/641869c2dab08ad68f69d6ba).

- What People Learn From Twitter: Evidence from a Panel Survey Combined with Direct Observation of Social Media Activity. Paper with Greogy Eady, Richard Bonneau, Joshua Tucker and Jonathan Nagler. [MPSA Slides](https://zilinskyjan.github.io/slides/MPSA_2019_Twitter.pdf).

- The Distinctness of Social and Economic Identities. With Suzanna Linn, Jonathan Nagler. <br>
[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4108071) | [Local pre-print](https://zilinskyjan.github.io/papers/Economic_Identity_2022.pdf)

<!-- - "People Like Me Are Falling Behind:" Measuring Perceptions of Inequality Using Novel Survey Questions.
Paper with Suzanna Linn, Jonathan Nagler, and Nathan Morse.-->

- Social Status and Beliefs in Conspiracy Theories. With Spyros Kosmidis and Yannis Theocharis.

- Justifying an Invasion: Where and Why is Disinformation Successful? (with many co-authors)

- Predicting Economic Evaluations. A methodological [summary](https://osf.io/7bgne/).

#### Other publications and links

- Is the FBI Impartial? Over Half of Republicans Say ‘No.’ Allegations of Political Biases in Law Enforcement Can Hurt Democracy. With Jonathan Ladd, Sean Kates, and Joshua Tucker. Washington Post ([Monkey Cage analysis](https://www.washingtonpost.com/politics/2022/09/15/fbi-trump-republicans-democrats-maga/)). Sept. 2022.
- Affective polarization and belief in voter fraud. ([Monkey Cage](https://www.washingtonpost.com/politics/2021/01/19/which-republicans-think-election-was-stolen-those-who-hate-democrats-dont-mind-white-nationalists/), January 2021.) [Supplementary analysis](https://csmapnyu.org/assets/publications/2021_03_02_TMC_fraud.pdf)
- Trump supporters who think he didn't keep his promises are more likely to vote for Joe Biden in 2020. ([Monkey Cage](https://www.washingtonpost.com/politics/2020/10/28/did-trump-keep-his-campaign-promises-heres-what-americans-think/), October 2020)
- The Political Logic of Standing with Trump against the Squad ([Washington Post, Monkey Cage analysis](https://www.washingtonpost.com/politics/2019/07/20/why-didnt-more-congressional-republicans-condemn-trumps-racist-tweets-about-squad-this-graph-explains/))
* [Ideological estimation with Twitter data](https://www.washingtonpost.com/news/monkey-cage/wp/2018/10/05/trying-to-understand-how-jeff-flake-is-leaning-we-analyzed-his-twitter-feed-and-were-surprised/?utm_term=.6036368712fe). [Methodological supplement](https://gregoryeady.com/Misc/Monkey_Cage_Flake_Methods_Supplement.pdf) explaining approach.
* Fiscal tightening and economic growth ([VoxEu.org](https://voxeu.org/article/fiscal-tightening-and-economic-growth-exploring-cross-country-correlations))
* Article in [Raising Lower-Level Wages: When and Why It Makes Economic Sense](https://www.piie.com/publications/piie-briefings/raising-lower-level-wages-when-and-why-it-makes-economic-sense)

## Links

* [Survey questions I wrote](https://zilinskyjan.github.io/surveys)

* [Trump studies (papers about the Trump 2016 victory)](https://zilinskyjan.github.io/trump-election-research) 

## Teaching

- [Conspiracy Theories and Politics](https://www.craft.do/s/vtoANButumlrdy) (Winter 2021, Spring 2022, Winter 2022)
- Campaigns, Elections, and Social Media (Winter 2022, Spring 2023)
- Telling stories with R and Data Visualization (Winter 2022, Spring 2023)
- [Information](https://zilinskyjan.github.io/prospective-students) for prospective students & thesis writers
